#### helper tutorials 
#### https://medium.com/@yongsun.yoon/fine-tuning-yolov8-using-custom-dataset-generated-by-open-world-object-detector-5724e267645d
#### [Converting a custom dataset from COCO format to YOLO format](https://medium.com/red-buffer/converting-a-custom-dataset-from-coco-format-to-yolo-format-6d98a4fd43fc)

#### [Fine-tuning YOLOv8 with Custom Dataset Generated by Open-world Object Detector](https://medium.com/@yongsun.yoon/fine-tuning-yolov8-using-custom-dataset-generated-by-open-world-object-detector-5724e267645d)

#### [Ultralytics YOLOv8 Docs](https://docs.ultralytics.com/modes/)

import numpy as np
import seaborn as sns
import os # for handling the directory
# from google.colab import drive # to access the drive
import shutil
import json
import tqdm

from ultralytics import YOLO


checkpoint = "weights/best.pt"
yolo = YOLO(checkpoint)
results = yolo.train(data='doclaynet_large.yaml', 
                    epochs=300, 
                    device=[2, 3, 4],
                    batch = 210,
                    optimizer = 'AdamW',
                    seed = 42,
                    profile = True,
                    plots = True,
                    dropout=0.2,
                    patience = 20,
                     # name = "epochs200_batch_128"

        )
valid_results = yolo.val(save_json=True,
                         device=[2, 3, 4],
                         batch=210,
                         conf=0.25,
                         plots=True,
                         )
print("*****************************Validation Results******************************")
